name: Terraform Apply

on:
  push:
    branches: [ main ]

jobs:
  apply:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 
    
    - name: Connect Tailscale
      uses: jaxxstorm/tailscale-github-action@c688cd1540188ec187964b96578a776c71b98136
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        version: latest
        tags: tag:ci

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Init
      id: init
      run: terraform init -no-color

    - name: Get PR and Run ID
      id: pr_run
      run: |
        echo "Current SHA: ${{ github.sha }}"
        echo "Current ref: ${{ github.ref }}"
        PR_NUMBER=$(git log -1 --pretty=%B | grep -oP '#\K\d+' | head -1)
        if [ -z "$PR_NUMBER" ]; then
          echo "No PR number found in commit message"
          PR_NUMBER=$(gh pr list --base ${{ github.ref_name }} --head ${{ github.sha }} --json number --jq '.[0].number')
        fi
        echo "PR number: $PR_NUMBER"
        echo "pr_number=$PR_NUMBER" >> $GITHUB_OUTPUT
        
        if [ ! -z "$PR_NUMBER" ]; then
          RUN_ID=$(gh run list --limit 100 --json databaseId,headBranch --jq ".[] | select(.headBranch == \"refs/pull/$PR_NUMBER/merge\") | .databaseId" | head -1)
          echo "Run ID for PR #$PR_NUMBER: $RUN_ID"
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


    - name: Download Terraform Plan
      uses: actions/download-artifact@v4
      with:
        name: tfplan
        run-id: ${{ github.event.workflow_run.id }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
  

    - name: Check for downloaded plan
      id: check_plan
      run: |
        if [ -f "tfplan" ]; then
          echo "Downloaded plan found"
          echo "plan_exists=true" >> $GITHUB_OUTPUT
        else
          echo "No downloaded plan found"
          echo "plan_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Terraform Plan (if no existing plan)
      if: steps.check_plan.outputs.plan_exists != 'true'
      id: plan
      run: terraform plan -no-color -out=tfplan
      env:
        TF_VAR_tailscale_auth_key_dev: ${{ secrets.TAILSCALE_AUTH_KEY_DEV }}
        TF_VAR_tailscale_auth_key_prod: ${{ secrets.TAILSCALE_AUTH_KEY_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2

    - name: Terraform Apply
      id: apply
      run: terraform apply -no-color -auto-approve tfplan
      env:
        TF_VAR_tailscale_auth_key_dev: ${{ secrets.TAILSCALE_AUTH_KEY_DEV }}
        TF_VAR_tailscale_auth_key_prod: ${{ secrets.TAILSCALE_AUTH_KEY_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2