name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TERRAFORM_CLOUD_TOKENS: app.terraform.io=${{ secrets.TF_API_TOKEN }}
    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4


    - name: Network Debugging with Netshoot before Tailscale
      run: |
        docker run --rm nicolaka/netshoot:latest /bin/bash -c '
        echo "===== DNS Configuration ====="
        cat /etc/resolv.conf
        echo "\n===== Network Interfaces ====="
        ip addr
        echo "\n===== Routing Table ====="
        ip route
        echo "\n===== DNS Resolution Test ====="
        nslookup releases.hashicorp.com
        nslookup github.com
        '
    
    - name: Connect Tailscale
      uses: jaxxstorm/tailscale-github-action@c688cd1540188ec187964b96578a776c71b98136
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
        version: latest
        tags: tag:ci

    - name: Network Debugging with Netshoot
      run: |
        docker run --rm nicolaka/netshoot:latest /bin/bash -c '
        echo "===== DNS Configuration ====="
        cat /etc/resolv.conf
        echo "\n===== Network Interfaces ====="
        ip addr
        echo "\n===== Routing Table ====="
        ip route
        echo "\n===== DNS Resolution Test ====="
        nslookup releases.hashicorp.com
        nslookup github.com
        echo "\n===== Outbound connectivity ====="
        ping -c 4 8.8.8.8
        '

    - name: terraform plan
      uses: dflook/terraform-plan@v1
      with:
        workspace: main
      env:
        TF_VAR_tailscale_auth_key_dev: ${{ secrets.TAILSCALE_AUTH_KEY_DEV }}
        TF_VAR_tailscale_auth_key_prod: ${{ secrets.TAILSCALE_AUTH_KEY_PROD }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-west-2